language: python
python:
  - "3.4"
  - "3.5"

install:
  - pip install --editable .
  - pip install --upgrade codecov
  - pip install --upgrade pytest pytest-cov

script: make pytest

after_success:
  codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18a32845ab49f23362e7
    on_success: change
    on_failure: always
    on_start: never
